// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace inventoryApp.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20260723131134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_price");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family");

                    b.Property<bool>("HasTVA")
                        .HasColumnType("boolean")
                        .HasColumnName("has_tva");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sell_price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StockEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("col_pos");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row_pos");

                    b.HasKey("Id")
                        .HasName("pk_stock_entries");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_stock_entries_location_id");

                    b.HasIndex("ProductId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_entries_product_id_location_id");

                    b.ToTable("stock_entries", null, t =>
                        {
                            t.HasCheckConstraint("quantity_not_negative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("FromLocationId")
                        .HasDatabaseName("ix_stock_movements_from_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_movements_product_id");

                    b.HasIndex("ToLocationId")
                        .HasDatabaseName("ix_stock_movements_to_id");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("different_source_destination", "from_id IS DISTINCT FROM to_id");

                            t.HasCheckConstraint("movement_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("StockEntry", b =>
                {
                    b.HasOne("Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_entries_locations_location_id");

                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_entries_products_product_id");
                });

            modelBuilder.Entity("StockMovement", b =>
                {
                    b.HasOne("Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movements_locations_from_id");

                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_id");

                    b.HasOne("Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movements_locations_to_id");
                });
#pragma warning restore 612, 618
        }
    }
}
